### ISSUE TITLE
How to debug case "GET TEXT ERROR" ?

### ISSUE THREAD

**Issue by Pakinwet** [paulstelzer/cordova-plugin-ml-kit#1]
Hi,
How do you debug case "GET TEXT ERROR" ?

![image-debug](https://user-images.githubusercontent.com/9396436/47603491-b1af6e00-da16-11e8-8a82-9e80aed1ea9f.png)

Thank you in advance for your kind support. 😊

**Comment by paulstelzer** [comment]
Could you please show your source code? If you copied the code from the demo, I fixed it few seconds ago because that code was wrong.

In general, you can open Android Studio. There you see all errors with stack trace.

**Comment by Pakinwet** [comment]
My source code :) 

`var takePhotoApp = {
    init: function(){
    	console.log("Start");
        document.getElementById('btn').addEventListener('click', takePhotoApp.takephoto);
    },
    takephoto: function(){
        let opts = {
            quality: 80,
            destinationType: Camera.DestinationType.FILE_URI,
            sourceType: Camera.PictureSourceType.CAMERA,
            mediaType: Camera.MediaType.PICTURE,
            encodingType: Camera.EncodingType.JPEG,
            cameraDirection: Camera.Direction.BACK,
            targetWidth: 300,
            targetHeight: 400
        };
        
        navigator.camera.getPicture(takePhotoApp.takephoto_success, takePhotoApp.takephoto_error, opts);
        console.log('takephoto');
    },
    takephoto_success: function(imgURI){
        document.getElementById('msg').textContent = imgURI;
        document.getElementById('photo').src = imgURI;

        console.log('Connect MlKitPlugin');
        //Add plugin MlKitPlugin
        window['MlKitPlugin'].getText(imgURI,
        (success) => {
          console.log('GET TEXT SUCCESS', success);
        },
        (error) => {
          console.log(error);
          console.log('GET TEXT ERROR', error);
        });

        console.log('Process getText ...');


        window['MlKitPlugin'].getTextCloud(imgURI,
        (success) => {
            console.log('GET TEXT CLOUD SUCCESS', success);
        },
        (error) => {
            console.log(error);
            console.log('GET TEXT CLOUD ERROR', error);
        });

        console.log('Process getTextCloud ...');

        
    },
    takephoto_error: function(msg){
        document.getElementById('msg').textContent = msg;
    }
};`

Thank you @paulstelzer

**Comment by Pakinwet** [comment]
After I updated plugin and code it work for me :)
`
window['MlKitPlugin'].getText(imgURI, {},
                    (success) => {
                      console.log('GET TEXT SUCCESS', success);
                    },
                    (error) => {
                      console.log(error);
                      console.log('GET TEXT ERROR', error);
                    });
`

Thank you @paulstelzer

**Comment by paulstelzer** [comment]
Yeah, you missed the options parameter like me in the demo ;)
